# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

parameters:
  - name: environ
    displayName: Environment
    type: string
    default: dev
    values:
    - dev
    - test
    - uat

resources:
- repo: self

variables:
  isDev: ${{eq(parameters.environ, 'dev')}}
  isTest: ${{eq(parameters.environ, 'test')}}
  isUat: ${{eq(parameters.environ, 'test')}}
  isProd: false
  tag: '$(Build.BuildId)'

stages:
- stage: validate
  displayName: validate
  jobs:
  - job: validateYaml
    displayName: validate yaml
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: echo isDev = $(isDev), isTest = $(isTest), isUat=$(isUat), isProd=$(isProd)
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Maven@3
      displayName: Maven build
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
