# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- multi-env-pipeline
name: buildp
parameters:
  - name: dev
    displayName: DEV
    type: boolean
    default: false
  - name: test
    displayName: TEST
    type: boolean
    default: false
  - name: uat
    displayName: UAT
    type: boolean
    default: false
  - name: prod
    displayName: PROD
    type: boolean
    default: false
  

resources:
- repo: self


variables:
# All the below code will be based on these flags. The condition for flag can be changed in one place here
# Example: Say, tomorrow we want to determine dev by branch name etc.
- name: isDev
  value: ${{eq(parameters.dev, true)}}
- name: isTest
  value: ${{eq(parameters.test, true)}}
- name: isUat
  value: ${{eq(parameters.uat, true)}}
- name: isProd
  value: ${{eq(parameters.prod, true)}}
- name: tag
  value: '$(Build.BuildId)'

stages:
- stage: validate
  condition: eq(variables.isDev, true)
  displayName: validate
  jobs:
  - job: validateYaml
    displayName: validate yaml
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: echo isDev = $(isDev), isTest = $(isTest), isUat=$(isUat), isProd=$(isProd)
- stage: Build
  displayName: Build image
  condition: or(eq(variables.isProd, true), eq(variables.isTest, true))
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Maven@3
      displayName: Maven build
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    
    - task: Docker@2
      condition: eq(variables.isProd, true)
      displayName: Build an image - only for prod
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
