# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- re-trigger

parameters:
  - name: environ
    displayName: Environment
    type: string
    default: dev
    values:
    - dev
    - test
    - uat
    - prod
  - name: env-dev
    displayName: DEV
    type: boolean
    default: false

resources:
- repo: self

variables:
# All the below code will be based on these flags. The condition for flag can be changed in one place here
# Example: Say, tomorrow we want to determine dev by branch name etc.
- name: isDev
  value: ${{eq(parameters.environ, 'dev')}}
- name: isTest
  value: ${{eq(parameters.environ, 'test')}}
- name: isUat
  value: ${{eq(parameters.environ, 'test')}}
- name: isProd
  value: ${{eq(parameters.environ, 'prod')}}
- name: tag
  value: '$(Build.BuildId)'

stages:
- stage: validate
  condition: eq(variables.isDev, true)
  displayName: validate
  jobs:
  - job: validateYaml
    displayName: validate yaml
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: echo env-dev=$(env-dev), isDev = $(isDev), isTest = $(isTest), isUat=$(isUat), isProd=$(isProd)
- stage: Build
  displayName: Build image
  condition: or(eq(variables.isProd, true), eq(variables.isTest, true))
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Maven@3
      displayName: Maven build
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    
    - task: Docker@2
      condition: eq(variables.isProd, true)
      displayName: Build an image - only for prod
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
- stage: ReTriggerIfApplicable
  displayName: Retrigger
  jobs:
    - job: 
      steps:
      - template: re-trigger.yaml
